#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPMOK.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ICT_mOK_KPP")]
	public partial class DB_MOKDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_GROUP_PERMISION(TBL_M_GROUP_PERMISION instance);
    partial void UpdateTBL_M_GROUP_PERMISION(TBL_M_GROUP_PERMISION instance);
    partial void DeleteTBL_M_GROUP_PERMISION(TBL_M_GROUP_PERMISION instance);
    partial void InsertTBL_R_MENU(TBL_R_MENU instance);
    partial void UpdateTBL_R_MENU(TBL_R_MENU instance);
    partial void DeleteTBL_R_MENU(TBL_R_MENU instance);
    partial void InsertTBL_T_ANNOUNCEMENT(TBL_T_ANNOUNCEMENT instance);
    partial void UpdateTBL_T_ANNOUNCEMENT(TBL_T_ANNOUNCEMENT instance);
    partial void DeleteTBL_T_ANNOUNCEMENT(TBL_T_ANNOUNCEMENT instance);
    partial void InsertTBL_M_APP_VERSION(TBL_M_APP_VERSION instance);
    partial void UpdateTBL_M_APP_VERSION(TBL_M_APP_VERSION instance);
    partial void DeleteTBL_M_APP_VERSION(TBL_M_APP_VERSION instance);
    partial void InsertTBL_R_USER_PHONE(TBL_R_USER_PHONE instance);
    partial void UpdateTBL_R_USER_PHONE(TBL_R_USER_PHONE instance);
    partial void DeleteTBL_R_USER_PHONE(TBL_R_USER_PHONE instance);
    partial void InsertTBL_T_NOTIFICATIONS_ON_DEMAND(TBL_T_NOTIFICATIONS_ON_DEMAND instance);
    partial void UpdateTBL_T_NOTIFICATIONS_ON_DEMAND(TBL_T_NOTIFICATIONS_ON_DEMAND instance);
    partial void DeleteTBL_T_NOTIFICATIONS_ON_DEMAND(TBL_T_NOTIFICATIONS_ON_DEMAND instance);
    #endregion
		
		public DB_MOKDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ICT_mOK_KPDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MOKDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MOKDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MOKDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MOKDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_KARYAWAN> VW_KARYAWANs
		{
			get
			{
				return this.GetTable<VW_KARYAWAN>();
			}
		}
		
		public System.Data.Linq.Table<VW_MENU> VW_MENUs
		{
			get
			{
				return this.GetTable<VW_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_DISTRIK> VW_DISTRIKs
		{
			get
			{
				return this.GetTable<VW_DISTRIK>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_MENU_GROUPING> TBL_M_MENU_GROUPINGs
		{
			get
			{
				return this.GetTable<TBL_M_MENU_GROUPING>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_GROUP_PERMISION> TBL_M_GROUP_PERMISIONs
		{
			get
			{
				return this.GetTable<TBL_M_GROUP_PERMISION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MENU> TBL_R_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_ANNOUNCEMENT> TBL_T_ANNOUNCEMENTs
		{
			get
			{
				return this.GetTable<TBL_T_ANNOUNCEMENT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_APP_VERSION> TBL_M_APP_VERSIONs
		{
			get
			{
				return this.GetTable<TBL_M_APP_VERSION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_USER_PHONE> TBL_R_USER_PHONEs
		{
			get
			{
				return this.GetTable<TBL_R_USER_PHONE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_KARYAWAN> TBL_M_KARYAWANs
		{
			get
			{
				return this.GetTable<TBL_M_KARYAWAN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_NOTIFICATIONS_ON_DEMAND> TBL_T_NOTIFICATIONS_ON_DEMANDs
		{
			get
			{
				return this.GetTable<TBL_T_NOTIFICATIONS_ON_DEMAND>();
			}
		}
		
		public System.Data.Linq.Table<VW_RECIPIENT> VW_RECIPIENTs
		{
			get
			{
				return this.GetTable<VW_RECIPIENT>();
			}
		}
		
		public System.Data.Linq.Table<VW_LOG> VW_LOGs
		{
			get
			{
				return this.GetTable<VW_LOG>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_insertDataPushNotifByNRP")]
		public int cusp_insertDataPushNotifByNRP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP", DbType="VarChar(10)")] string nRP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TITLE", DbType="VarChar(MAX)")] string tITLE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BODY", DbType="VarChar(MAX)")] string bODY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TARGET", DbType="VarChar(MAX)")] string tARGET, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVENTID", DbType="VarChar(MAX)")] string eVENTID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nRP, tITLE, bODY, tARGET, eVENTID);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KARYAWAN")]
	public partial class VW_KARYAWAN
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _BIRTH_DATE;
		
		private string _STATUS_EMPLOYEE;
		
		private string _hire_date;
		
		private string _END_KONTRAK_1;
		
		private string _END_KONTRAK_2;
		
		private string _GRADE;
		
		private string _POS_TITLE;
		
		private string _DEPT;
		
		private string _SITE;
		
		private string _POSITION_ID;
		
		public VW_KARYAWAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="NVarChar(8)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_EMPLOYEE", DbType="NVarChar(2)")]
		public string STATUS_EMPLOYEE
		{
			get
			{
				return this._STATUS_EMPLOYEE;
			}
			set
			{
				if ((this._STATUS_EMPLOYEE != value))
				{
					this._STATUS_EMPLOYEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hire_date", DbType="NVarChar(8)")]
		public string hire_date
		{
			get
			{
				return this._hire_date;
			}
			set
			{
				if ((this._hire_date != value))
				{
					this._hire_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_KONTRAK_1", DbType="NVarChar(8)")]
		public string END_KONTRAK_1
		{
			get
			{
				return this._END_KONTRAK_1;
			}
			set
			{
				if ((this._END_KONTRAK_1 != value))
				{
					this._END_KONTRAK_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_KONTRAK_2", DbType="NVarChar(8)")]
		public string END_KONTRAK_2
		{
			get
			{
				return this._END_KONTRAK_2;
			}
			set
			{
				if ((this._END_KONTRAK_2 != value))
				{
					this._END_KONTRAK_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="NVarChar(2)")]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this._GRADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="NVarChar(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_MENU")]
	public partial class VW_MENU
	{
		
		private System.Guid _MENU_PID;
		
		private string _MENU_DESC;
		
		private string _MENU_LINK;
		
		private string _MENU_LINK_IOS;
		
		private string _MENU_ICON;
		
		private string _DISTRICT;
		
		private System.Nullable<bool> _IS_DEFAULT;
		
		private System.Nullable<bool> _IS_SSO;
		
		private string _androidAppId;
		
		private string _iosAppId;
		
		private string _downloadUrl;
		
		private System.Nullable<int> _GROUP_ID;
		
		private string _GROUPING;
		
		private System.Nullable<bool> _IS_AVAILABLE;
		
		private string _ACL_GROUP_NAME;
		
		private string _DEPT_GROUP_NAME;
		
		public VW_MENU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_PID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid MENU_PID
		{
			get
			{
				return this._MENU_PID;
			}
			set
			{
				if ((this._MENU_PID != value))
				{
					this._MENU_PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_DESC", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MENU_DESC
		{
			get
			{
				return this._MENU_DESC;
			}
			set
			{
				if ((this._MENU_DESC != value))
				{
					this._MENU_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_LINK", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MENU_LINK
		{
			get
			{
				return this._MENU_LINK;
			}
			set
			{
				if ((this._MENU_LINK != value))
				{
					this._MENU_LINK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_LINK_IOS", DbType="VarChar(500)")]
		public string MENU_LINK_IOS
		{
			get
			{
				return this._MENU_LINK_IOS;
			}
			set
			{
				if ((this._MENU_LINK_IOS != value))
				{
					this._MENU_LINK_IOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ICON", DbType="VarChar(1000)")]
		public string MENU_ICON
		{
			get
			{
				return this._MENU_ICON;
			}
			set
			{
				if ((this._MENU_ICON != value))
				{
					this._MENU_ICON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(50)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this._DISTRICT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_DEFAULT", DbType="Bit")]
		public System.Nullable<bool> IS_DEFAULT
		{
			get
			{
				return this._IS_DEFAULT;
			}
			set
			{
				if ((this._IS_DEFAULT != value))
				{
					this._IS_DEFAULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_SSO", DbType="Bit")]
		public System.Nullable<bool> IS_SSO
		{
			get
			{
				return this._IS_SSO;
			}
			set
			{
				if ((this._IS_SSO != value))
				{
					this._IS_SSO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_androidAppId", DbType="VarChar(255)")]
		public string androidAppId
		{
			get
			{
				return this._androidAppId;
			}
			set
			{
				if ((this._androidAppId != value))
				{
					this._androidAppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iosAppId", DbType="VarChar(255)")]
		public string iosAppId
		{
			get
			{
				return this._iosAppId;
			}
			set
			{
				if ((this._iosAppId != value))
				{
					this._iosAppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloadUrl", DbType="VarChar(500)")]
		public string downloadUrl
		{
			get
			{
				return this._downloadUrl;
			}
			set
			{
				if ((this._downloadUrl != value))
				{
					this._downloadUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ID", DbType="Int")]
		public System.Nullable<int> GROUP_ID
		{
			get
			{
				return this._GROUP_ID;
			}
			set
			{
				if ((this._GROUP_ID != value))
				{
					this._GROUP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPING", DbType="VarChar(255)")]
		public string GROUPING
		{
			get
			{
				return this._GROUPING;
			}
			set
			{
				if ((this._GROUPING != value))
				{
					this._GROUPING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_AVAILABLE", DbType="Bit")]
		public System.Nullable<bool> IS_AVAILABLE
		{
			get
			{
				return this._IS_AVAILABLE;
			}
			set
			{
				if ((this._IS_AVAILABLE != value))
				{
					this._IS_AVAILABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACL_GROUP_NAME", DbType="VarChar(50)")]
		public string ACL_GROUP_NAME
		{
			get
			{
				return this._ACL_GROUP_NAME;
			}
			set
			{
				if ((this._ACL_GROUP_NAME != value))
				{
					this._ACL_GROUP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_GROUP_NAME", DbType="VarChar(50)")]
		public string DEPT_GROUP_NAME
		{
			get
			{
				return this._DEPT_GROUP_NAME;
			}
			set
			{
				if ((this._DEPT_GROUP_NAME != value))
				{
					this._DEPT_GROUP_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DISTRIK")]
	public partial class VW_DISTRIK
	{
		
		private string _DSTRCT_CODE;
		
		public VW_DISTRIK()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_MENU_GROUPING")]
	public partial class TBL_M_MENU_GROUPING
	{
		
		private int _ID_GROUP;
		
		private string _NAMA_GROUP;
		
		public TBL_M_MENU_GROUPING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GROUP", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_GROUP
		{
			get
			{
				return this._ID_GROUP;
			}
			set
			{
				if ((this._ID_GROUP != value))
				{
					this._ID_GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_GROUP", DbType="VarChar(50)")]
		public string NAMA_GROUP
		{
			get
			{
				return this._NAMA_GROUP;
			}
			set
			{
				if ((this._NAMA_GROUP != value))
				{
					this._NAMA_GROUP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_GROUP_PERMISION")]
	public partial class TBL_M_GROUP_PERMISION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GROUP_ID;
		
		private string _GROUP_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGROUP_IDChanging(int value);
    partial void OnGROUP_IDChanged();
    partial void OnGROUP_NAMEChanging(string value);
    partial void OnGROUP_NAMEChanged();
    #endregion
		
		public TBL_M_GROUP_PERMISION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GROUP_ID
		{
			get
			{
				return this._GROUP_ID;
			}
			set
			{
				if ((this._GROUP_ID != value))
				{
					this.OnGROUP_IDChanging(value);
					this.SendPropertyChanging();
					this._GROUP_ID = value;
					this.SendPropertyChanged("GROUP_ID");
					this.OnGROUP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_NAME", DbType="VarChar(50)")]
		public string GROUP_NAME
		{
			get
			{
				return this._GROUP_NAME;
			}
			set
			{
				if ((this._GROUP_NAME != value))
				{
					this.OnGROUP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._GROUP_NAME = value;
					this.SendPropertyChanged("GROUP_NAME");
					this.OnGROUP_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MENU")]
	public partial class TBL_R_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _MENU_PID;
		
		private string _MENU_DESC;
		
		private string _MENU_LINK;
		
		private string _MENU_LINK_IOS;
		
		private string _MENU_ICON;
		
		private string _DISTRICT;
		
		private System.Nullable<bool> _IS_DEFAULT;
		
		private System.Nullable<bool> _IS_SSO;
		
		private string _androidAppId;
		
		private string _iosAppId;
		
		private string _downloadUrl;
		
		private System.Nullable<int> _GROUP_ID;
		
		private string _GROUPING;
		
		private System.Nullable<bool> _IS_AVAILABLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMENU_PIDChanging(System.Guid value);
    partial void OnMENU_PIDChanged();
    partial void OnMENU_DESCChanging(string value);
    partial void OnMENU_DESCChanged();
    partial void OnMENU_LINKChanging(string value);
    partial void OnMENU_LINKChanged();
    partial void OnMENU_LINK_IOSChanging(string value);
    partial void OnMENU_LINK_IOSChanged();
    partial void OnMENU_ICONChanging(string value);
    partial void OnMENU_ICONChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnIS_DEFAULTChanging(System.Nullable<bool> value);
    partial void OnIS_DEFAULTChanged();
    partial void OnIS_SSOChanging(System.Nullable<bool> value);
    partial void OnIS_SSOChanged();
    partial void OnandroidAppIdChanging(string value);
    partial void OnandroidAppIdChanged();
    partial void OniosAppIdChanging(string value);
    partial void OniosAppIdChanged();
    partial void OndownloadUrlChanging(string value);
    partial void OndownloadUrlChanged();
    partial void OnGROUP_IDChanging(System.Nullable<int> value);
    partial void OnGROUP_IDChanged();
    partial void OnGROUPINGChanging(string value);
    partial void OnGROUPINGChanged();
    partial void OnIS_AVAILABLEChanging(System.Nullable<bool> value);
    partial void OnIS_AVAILABLEChanged();
    #endregion
		
		public TBL_R_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_PID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid MENU_PID
		{
			get
			{
				return this._MENU_PID;
			}
			set
			{
				if ((this._MENU_PID != value))
				{
					this.OnMENU_PIDChanging(value);
					this.SendPropertyChanging();
					this._MENU_PID = value;
					this.SendPropertyChanged("MENU_PID");
					this.OnMENU_PIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_DESC", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MENU_DESC
		{
			get
			{
				return this._MENU_DESC;
			}
			set
			{
				if ((this._MENU_DESC != value))
				{
					this.OnMENU_DESCChanging(value);
					this.SendPropertyChanging();
					this._MENU_DESC = value;
					this.SendPropertyChanged("MENU_DESC");
					this.OnMENU_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_LINK", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MENU_LINK
		{
			get
			{
				return this._MENU_LINK;
			}
			set
			{
				if ((this._MENU_LINK != value))
				{
					this.OnMENU_LINKChanging(value);
					this.SendPropertyChanging();
					this._MENU_LINK = value;
					this.SendPropertyChanged("MENU_LINK");
					this.OnMENU_LINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_LINK_IOS", DbType="VarChar(500)")]
		public string MENU_LINK_IOS
		{
			get
			{
				return this._MENU_LINK_IOS;
			}
			set
			{
				if ((this._MENU_LINK_IOS != value))
				{
					this.OnMENU_LINK_IOSChanging(value);
					this.SendPropertyChanging();
					this._MENU_LINK_IOS = value;
					this.SendPropertyChanged("MENU_LINK_IOS");
					this.OnMENU_LINK_IOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ICON", DbType="VarChar(1000)")]
		public string MENU_ICON
		{
			get
			{
				return this._MENU_ICON;
			}
			set
			{
				if ((this._MENU_ICON != value))
				{
					this.OnMENU_ICONChanging(value);
					this.SendPropertyChanging();
					this._MENU_ICON = value;
					this.SendPropertyChanged("MENU_ICON");
					this.OnMENU_ICONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(50)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_DEFAULT", DbType="Bit")]
		public System.Nullable<bool> IS_DEFAULT
		{
			get
			{
				return this._IS_DEFAULT;
			}
			set
			{
				if ((this._IS_DEFAULT != value))
				{
					this.OnIS_DEFAULTChanging(value);
					this.SendPropertyChanging();
					this._IS_DEFAULT = value;
					this.SendPropertyChanged("IS_DEFAULT");
					this.OnIS_DEFAULTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_SSO", DbType="Bit")]
		public System.Nullable<bool> IS_SSO
		{
			get
			{
				return this._IS_SSO;
			}
			set
			{
				if ((this._IS_SSO != value))
				{
					this.OnIS_SSOChanging(value);
					this.SendPropertyChanging();
					this._IS_SSO = value;
					this.SendPropertyChanged("IS_SSO");
					this.OnIS_SSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_androidAppId", DbType="VarChar(255)")]
		public string androidAppId
		{
			get
			{
				return this._androidAppId;
			}
			set
			{
				if ((this._androidAppId != value))
				{
					this.OnandroidAppIdChanging(value);
					this.SendPropertyChanging();
					this._androidAppId = value;
					this.SendPropertyChanged("androidAppId");
					this.OnandroidAppIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iosAppId", DbType="VarChar(255)")]
		public string iosAppId
		{
			get
			{
				return this._iosAppId;
			}
			set
			{
				if ((this._iosAppId != value))
				{
					this.OniosAppIdChanging(value);
					this.SendPropertyChanging();
					this._iosAppId = value;
					this.SendPropertyChanged("iosAppId");
					this.OniosAppIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloadUrl", DbType="VarChar(500)")]
		public string downloadUrl
		{
			get
			{
				return this._downloadUrl;
			}
			set
			{
				if ((this._downloadUrl != value))
				{
					this.OndownloadUrlChanging(value);
					this.SendPropertyChanging();
					this._downloadUrl = value;
					this.SendPropertyChanged("downloadUrl");
					this.OndownloadUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ID", DbType="Int")]
		public System.Nullable<int> GROUP_ID
		{
			get
			{
				return this._GROUP_ID;
			}
			set
			{
				if ((this._GROUP_ID != value))
				{
					this.OnGROUP_IDChanging(value);
					this.SendPropertyChanging();
					this._GROUP_ID = value;
					this.SendPropertyChanged("GROUP_ID");
					this.OnGROUP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPING", DbType="VarChar(255)")]
		public string GROUPING
		{
			get
			{
				return this._GROUPING;
			}
			set
			{
				if ((this._GROUPING != value))
				{
					this.OnGROUPINGChanging(value);
					this.SendPropertyChanging();
					this._GROUPING = value;
					this.SendPropertyChanged("GROUPING");
					this.OnGROUPINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_AVAILABLE", DbType="Bit")]
		public System.Nullable<bool> IS_AVAILABLE
		{
			get
			{
				return this._IS_AVAILABLE;
			}
			set
			{
				if ((this._IS_AVAILABLE != value))
				{
					this.OnIS_AVAILABLEChanging(value);
					this.SendPropertyChanging();
					this._IS_AVAILABLE = value;
					this.SendPropertyChanged("IS_AVAILABLE");
					this.OnIS_AVAILABLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_ANNOUNCEMENT")]
	public partial class TBL_T_ANNOUNCEMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _title;
		
		private string _body;
		
		private System.Nullable<int> _order;
		
		private string _imageUrl;
		
		private string _targetUrl;
		
		private string _type;
		
		private System.Nullable<int> _status;
		
		private string _location;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnorderChanging(System.Nullable<int> value);
    partial void OnorderChanged();
    partial void OnimageUrlChanging(string value);
    partial void OnimageUrlChanged();
    partial void OntargetUrlChanging(string value);
    partial void OntargetUrlChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    #endregion
		
		public TBL_T_ANNOUNCEMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="VarChar(MAX)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[order]", Storage="_order", DbType="Int")]
		public System.Nullable<int> order
		{
			get
			{
				return this._order;
			}
			set
			{
				if ((this._order != value))
				{
					this.OnorderChanging(value);
					this.SendPropertyChanging();
					this._order = value;
					this.SendPropertyChanged("order");
					this.OnorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageUrl", DbType="VarChar(200)")]
		public string imageUrl
		{
			get
			{
				return this._imageUrl;
			}
			set
			{
				if ((this._imageUrl != value))
				{
					this.OnimageUrlChanging(value);
					this.SendPropertyChanging();
					this._imageUrl = value;
					this.SendPropertyChanged("imageUrl");
					this.OnimageUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_targetUrl", DbType="VarChar(MAX)")]
		public string targetUrl
		{
			get
			{
				return this._targetUrl;
			}
			set
			{
				if ((this._targetUrl != value))
				{
					this.OntargetUrlChanging(value);
					this.SendPropertyChanging();
					this._targetUrl = value;
					this.SendPropertyChanged("targetUrl");
					this.OntargetUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_APP_VERSION")]
	public partial class TBL_M_APP_VERSION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _os_name;
		
		private string _app_version;
		
		private System.Nullable<System.DateTime> _release_date;
		
		private string _link_gdrive;
		
		private string _link_playstore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onos_nameChanging(string value);
    partial void Onos_nameChanged();
    partial void Onapp_versionChanging(string value);
    partial void Onapp_versionChanged();
    partial void Onrelease_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onrelease_dateChanged();
    partial void Onlink_gdriveChanging(string value);
    partial void Onlink_gdriveChanged();
    partial void Onlink_playstoreChanging(string value);
    partial void Onlink_playstoreChanged();
    #endregion
		
		public TBL_M_APP_VERSION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_os_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string os_name
		{
			get
			{
				return this._os_name;
			}
			set
			{
				if ((this._os_name != value))
				{
					this.Onos_nameChanging(value);
					this.SendPropertyChanging();
					this._os_name = value;
					this.SendPropertyChanged("os_name");
					this.Onos_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_version", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string app_version
		{
			get
			{
				return this._app_version;
			}
			set
			{
				if ((this._app_version != value))
				{
					this.Onapp_versionChanging(value);
					this.SendPropertyChanging();
					this._app_version = value;
					this.SendPropertyChanged("app_version");
					this.Onapp_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_release_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> release_date
		{
			get
			{
				return this._release_date;
			}
			set
			{
				if ((this._release_date != value))
				{
					this.Onrelease_dateChanging(value);
					this.SendPropertyChanging();
					this._release_date = value;
					this.SendPropertyChanged("release_date");
					this.Onrelease_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_gdrive", DbType="VarChar(500)")]
		public string link_gdrive
		{
			get
			{
				return this._link_gdrive;
			}
			set
			{
				if ((this._link_gdrive != value))
				{
					this.Onlink_gdriveChanging(value);
					this.SendPropertyChanging();
					this._link_gdrive = value;
					this.SendPropertyChanged("link_gdrive");
					this.Onlink_gdriveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_playstore", DbType="VarChar(500)")]
		public string link_playstore
		{
			get
			{
				return this._link_playstore;
			}
			set
			{
				if ((this._link_playstore != value))
				{
					this.Onlink_playstoreChanging(value);
					this.SendPropertyChanging();
					this._link_playstore = value;
					this.SendPropertyChanged("link_playstore");
					this.Onlink_playstoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_USER_PHONE")]
	public partial class TBL_R_USER_PHONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nrp;
		
		private string _phoneNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnrpChanging(string value);
    partial void OnnrpChanged();
    partial void OnphoneNoChanging(string value);
    partial void OnphoneNoChanged();
    #endregion
		
		public TBL_R_USER_PHONE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this.OnnrpChanging(value);
					this.SendPropertyChanging();
					this._nrp = value;
					this.SendPropertyChanged("nrp");
					this.OnnrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNo", DbType="VarChar(50)")]
		public string phoneNo
		{
			get
			{
				return this._phoneNo;
			}
			set
			{
				if ((this._phoneNo != value))
				{
					this.OnphoneNoChanging(value);
					this.SendPropertyChanging();
					this._phoneNo = value;
					this.SendPropertyChanged("phoneNo");
					this.OnphoneNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_KARYAWAN")]
	public partial class TBL_M_KARYAWAN
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _BIRTH_DATE;
		
		private string _STATUS_EMPLOYEE;
		
		private string _hire_date;
		
		private string _END_KONTRAK_1;
		
		private string _END_KONTRAK_2;
		
		private string _GRADE;
		
		private string _POS_TITLE;
		
		private string _DEPT;
		
		private string _SITE;
		
		private string _POSITION_ID;
		
		private string _NIK;
		
		public TBL_M_KARYAWAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="NVarChar(8)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_EMPLOYEE", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string STATUS_EMPLOYEE
		{
			get
			{
				return this._STATUS_EMPLOYEE;
			}
			set
			{
				if ((this._STATUS_EMPLOYEE != value))
				{
					this._STATUS_EMPLOYEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hire_date", DbType="NVarChar(8)")]
		public string hire_date
		{
			get
			{
				return this._hire_date;
			}
			set
			{
				if ((this._hire_date != value))
				{
					this._hire_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_KONTRAK_1", DbType="NVarChar(8)")]
		public string END_KONTRAK_1
		{
			get
			{
				return this._END_KONTRAK_1;
			}
			set
			{
				if ((this._END_KONTRAK_1 != value))
				{
					this._END_KONTRAK_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_KONTRAK_2", DbType="NVarChar(8)")]
		public string END_KONTRAK_2
		{
			get
			{
				return this._END_KONTRAK_2;
			}
			set
			{
				if ((this._END_KONTRAK_2 != value))
				{
					this._END_KONTRAK_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="NVarChar(2)")]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this._GRADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="NVarChar(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIK", DbType="VarChar(100)")]
		public string NIK
		{
			get
			{
				return this._NIK;
			}
			set
			{
				if ((this._NIK != value))
				{
					this._NIK = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_NOTIFICATIONS_ON_DEMAND")]
	public partial class TBL_T_NOTIFICATIONS_ON_DEMAND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _recipient;
		
		private string _title;
		
		private string _sound;
		
		private string _body;
		
		private string _target;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<System.DateTime> _date_sent;
		
		private System.Nullable<System.DateTime> _date_create;
		
		private string _remarks;
		
		private string _event_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrecipientChanging(string value);
    partial void OnrecipientChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnsoundChanging(string value);
    partial void OnsoundChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OntargetChanging(string value);
    partial void OntargetChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Ondate_sentChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_sentChanged();
    partial void Ondate_createChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_createChanged();
    partial void OnremarksChanging(string value);
    partial void OnremarksChanged();
    partial void Onevent_idChanging(string value);
    partial void Onevent_idChanged();
    #endregion
		
		public TBL_T_NOTIFICATIONS_ON_DEMAND()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recipient", DbType="VarChar(MAX)")]
		public string recipient
		{
			get
			{
				return this._recipient;
			}
			set
			{
				if ((this._recipient != value))
				{
					this.OnrecipientChanging(value);
					this.SendPropertyChanging();
					this._recipient = value;
					this.SendPropertyChanged("recipient");
					this.OnrecipientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sound", DbType="VarChar(MAX)")]
		public string sound
		{
			get
			{
				return this._sound;
			}
			set
			{
				if ((this._sound != value))
				{
					this.OnsoundChanging(value);
					this.SendPropertyChanging();
					this._sound = value;
					this.SendPropertyChanged("sound");
					this.OnsoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="VarChar(MAX)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target", DbType="VarChar(MAX)")]
		public string target
		{
			get
			{
				return this._target;
			}
			set
			{
				if ((this._target != value))
				{
					this.OntargetChanging(value);
					this.SendPropertyChanging();
					this._target = value;
					this.SendPropertyChanged("target");
					this.OntargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_sent", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_sent
		{
			get
			{
				return this._date_sent;
			}
			set
			{
				if ((this._date_sent != value))
				{
					this.Ondate_sentChanging(value);
					this.SendPropertyChanging();
					this._date_sent = value;
					this.SendPropertyChanged("date_sent");
					this.Ondate_sentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_create", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_create
		{
			get
			{
				return this._date_create;
			}
			set
			{
				if ((this._date_create != value))
				{
					this.Ondate_createChanging(value);
					this.SendPropertyChanging();
					this._date_create = value;
					this.SendPropertyChanged("date_create");
					this.Ondate_createChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="VarChar(MAX)")]
		public string remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				if ((this._remarks != value))
				{
					this.OnremarksChanging(value);
					this.SendPropertyChanging();
					this._remarks = value;
					this.SendPropertyChanged("remarks");
					this.OnremarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="VarChar(MAX)")]
		public string event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_RECIPIENTS")]
	public partial class VW_RECIPIENT
	{
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<System.DateTime> _expiredDate;
		
		private string _otp;
		
		private string _token;
		
		private string _device_id;
		
		private string _SITE;
		
		private string _NAME;
		
		private string _GRADE;
		
		private string _GENDER_CODE;
		
		private string _GENDER_DESC;
		
		private string _MARITAL_STATUS;
		
		private string _MARITAL_STATUS_DESC;
		
		private string _POS_TITLE;
		
		private string _DEPT;
		
		public VW_RECIPIENT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> expiredDate
		{
			get
			{
				return this._expiredDate;
			}
			set
			{
				if ((this._expiredDate != value))
				{
					this._expiredDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otp", DbType="VarChar(50)")]
		public string otp
		{
			get
			{
				return this._otp;
			}
			set
			{
				if ((this._otp != value))
				{
					this._otp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_id", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				if ((this._device_id != value))
				{
					this._device_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="NVarChar(2)")]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this._GRADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_DESC", DbType="VarChar(100)")]
		public string GENDER_DESC
		{
			get
			{
				return this._GENDER_DESC;
			}
			set
			{
				if ((this._GENDER_DESC != value))
				{
					this._GENDER_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARITAL_STATUS", DbType="VarChar(100)")]
		public string MARITAL_STATUS
		{
			get
			{
				return this._MARITAL_STATUS;
			}
			set
			{
				if ((this._MARITAL_STATUS != value))
				{
					this._MARITAL_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARITAL_STATUS_DESC", DbType="VarChar(100)")]
		public string MARITAL_STATUS_DESC
		{
			get
			{
				return this._MARITAL_STATUS_DESC;
			}
			set
			{
				if ((this._MARITAL_STATUS_DESC != value))
				{
					this._MARITAL_STATUS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LOGS")]
	public partial class VW_LOG
	{
		
		private int _headerID;
		
		private string _username;
		
		private string _device_id;
		
		private string _os_name;
		
		private string _token;
		
		private string _actionAPI;
		
		private string _remarks;
		
		private System.Nullable<System.DateTime> _insertDate;
		
		private string _AppVersion;
		
		public VW_LOG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headerID", DbType="Int NOT NULL")]
		public int headerID
		{
			get
			{
				return this._headerID;
			}
			set
			{
				if ((this._headerID != value))
				{
					this._headerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_id", DbType="VarChar(MAX)")]
		public string device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				if ((this._device_id != value))
				{
					this._device_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_os_name", DbType="VarChar(MAX)")]
		public string os_name
		{
			get
			{
				return this._os_name;
			}
			set
			{
				if ((this._os_name != value))
				{
					this._os_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(MAX)")]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionAPI", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string actionAPI
		{
			get
			{
				return this._actionAPI;
			}
			set
			{
				if ((this._actionAPI != value))
				{
					this._actionAPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="VarChar(MAX)")]
		public string remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				if ((this._remarks != value))
				{
					this._remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insertDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> insertDate
		{
			get
			{
				return this._insertDate;
			}
			set
			{
				if ((this._insertDate != value))
				{
					this._insertDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppVersion", DbType="VarChar(MAX)")]
		public string AppVersion
		{
			get
			{
				return this._AppVersion;
			}
			set
			{
				if ((this._AppVersion != value))
				{
					this._AppVersion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
